version: "3"
services:
  # Infrastructure
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nms
    networks: 
      - nms
  mongo:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    networks: 
      - nms
  activemq:
    image: rmohr/activemq
    hostname: activemq
    restart: always
    expose:
      - "5672"
    ports:
      - "5672:5672"
    networks: 
      - nms
  # Base services
  api-gateway:
    image: multiversenms/api-gateway:latest
    hostname: api-gateway
    restart: always
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    networks: 
      - nms
  telemetry-microservice:
    image: multiversenms/telemetry:latest
    restart: always
    depends_on:
      - mongo
      - activemq
    expose:
      - "8082"
    networks:
      - nms
  topology-microservice:
    image: multiversenms/topology:latest
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "8085"
    networks: 
      - nms
  fault-microservice:
    image: multiversenms/fault:latest
    restart: always
    expose:
      - "8084"
    networks:
      - nms
  # Optical services
  qconnection-microservice:
    image: multiversenms/qconnection:latest
    restart: always
    depends_on:
      - topology-microservice
    environment:
      - B205=${B205}
      - GCF=${GCF}
    expose:
      - "8090"
    networks:
      - nms
  oxcdevice-microservice:
    image: multiversenms/oxcdevice:latest
    restart: always
    depends_on:
      - topology-microservice
    environment:
      - B205=${B205}
      - GCF=${GCF}
    expose:
      - "8091"
    ports:
      - "1234:1234/udp"
    networks:
      - nms
  path-microservice:
    image: multiversenms/path:latest
    restart: always
    depends_on:
      - topology-microservice
    expose:
      - "8092"
    networks:
      - nms
  # IP services
  #ipcollect-microservice:
  #  image: multiversenms/ipcollect:latest
  #  environment:
  #    - CONTROLLER=${SERVER_IP}
  #    - AMQP_BROKER=${SERVER_IP}
  #  expose:
  #    - "8071"
  #  networks:
  #    - nms
  #ipconfig-microservice:
  #  image: multiversenms/ipconfig:latest
  #  environment:
  #    - CONTROLLER=${SERVER_IP}
  #    - AMQP_BROKER=${SERVER_IP}
  #  expose:
  #    - "8072"
  #  networks:
  #    - nms

  # User access
  postgresql:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - nms
  keycloak:
    image: docker.io/bitnami/keycloak
    restart: always
    environment:
      - KEYCLOAK_HTTP_PORT=8888
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    depends_on:
      - postgresql
    ports:
      - "8888:8888"
    volumes:
      - ./kc_config.json:/opt/bitnami/keycloak/data/import/kc_config.json
    networks:
      - nms

  # GUI
  multiverse-gui:
    image: multiversenms/gui:latest
    depends_on:
      - api-gateway
    environment:
      - VUE_APP_SERVER=${SERVER_IP}
    ports:
      - "8080:80"
    networks:
      - nms

volumes:
  postgresql_data:
    driver: local
networks:
  nms:
    driver: bridge
